public_folder: public
services:
  check_risp:
    evaluator: [python, services/python/simple/check_risp_server.py]
    args:
      num_pills:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 5
      risp:
        regex: ^([1-9][0-9]{0,50})$
        default: 100
      answ_mod:
        regex: ^([1-9][0-9]{0,10})$
        default: 1000000007
      sorting_criterion:
        regex: ^(dislike_half_pills|dislike_integer_pills)$
        default: dislike_half_pills
      list_them_out_if_right:
        regexp: ^(0|1)$
        default: 0
      more_or_less_hint_if_wrong:
        regexp: ^(0|1)$
        default: 0
      with_evidence_if_more:
        regexp: ^(0|1)$
        default: 0
      add_extrahint_if_less:
        regexp: ^(0|1)$
        default: 0
      lang:
        regex: ^(en|it)$
        default: it
  score_risp:
    evaluator: [python, services/python/simple/score_risp_server.py]
    args:
      answ_mod:
        regex: ^([1-9][0-9]{0,10})$
        default: 1000000007
      lang:
        regex: ^(en|it)$
        default: it
  check_list:
    evaluator: [python, services/python/simple/check_list_server.py]
    args:
      num_pills:
        regex: ^([1-9]|1[0-9]{0,1}|20)$
        default: 5
      sorting_criterion:
        regex: ^(None|dislike_half_pills|dislike_integer_pills)$
        default: dislike_half_pills
      spot_wrong_consec_if_sorted:
        regexp: ^(0|1)$
        default: 0
      tell_shortest_missing_prefix:
        regexp: ^(0|1)$
        default: 0
      give_one_missing:
        regexp: ^(0|1)$
        default: 0
      lang:
        regex: ^(en|it)$
        default: it
  score_list:
    evaluator: [python, services/python/simple/score_list_server.py]
    args:
      sorting_criterion:
        regex: ^(None|dislike_half_pills|dislike_integer_pills)$
        default: dislike_half_pills
      lang:
        regex: ^(en|it)$
        default: it
  check_next:
    evaluator: [python, services/python/simple/check_next_sol.py]
    args:
      current_sol:
        regex:  ^(I|H){1,1000}$
        default: I
      next_sol:
        regex:  ^(I|H){1,1000}$
        default: HH
      sorting_criterion:
        regex: ^(dislike_half_pills|dislike_integer_pills)$
        default: dislike_half_pills
      tell_first_mistake:
        regexp: ^(0|1)$
        default: 0
      tell_first_mistake:
        regexp: ^(0|1)$
        default: 0
      lang:
        regex: ^(en|it)$
        default: it
  score_next:
    evaluator: [python, services/python/simple/score_next_sol_server.py]
    args:
      sorting_criterion:
        regex: ^(dislike_half_pills|dislike_integer_pills)$
        default: dislike_half_pills
      lang:
        regex: ^(en|it)$
        default: it
  recognize:
    evaluator: [python, services/python/simple/recognize_server.py]
    args:
      lang:
        regex: ^(en|it)$
        default: it
