%YAML 1.2
---
public_folder: public
services:
  bigger_and_bigger:
    evaluator: [python, services/bigger_and_bigger/simple/bigger_and_bigger_driver.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 20
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  rationals_are_dense_into_reals:
    evaluator: [python, services/archimede/simple/archimede_driver.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 10
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  archimede:
    evaluator: [python, services/archimede/simple/archimede_driver.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 10
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_driver.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
        explain: any string without space characters but meant to specify one of the services of the problem {problem}
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
      metafile:
        regex: ^(main|en|it)$
        default: main
...
