codename: TestArgumentsMulti
attachments_folder: att
services:
  print:
    evaluator: solve.py
    args:
      num: 
        regex: ([0-9]*)
        defualt: 0
      num2: 
        regex: ([0-9]*)
        defualt: 1
