public_folder: public
services:
  game123:
    explain: "Which is the best move 1,2,3 ? Or you have lose from begging? "
    evaluator: [python, services/game123_server.py]
    args:
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
        explain: "Number from 1 to 30, the number of questions posed to the problem solver."
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  game123_interactive:
    explain: "Which is the best move 1,2,3 ? Or you have lose from begging? Play with a strong mate."
    evaluator: [python, services/game123_interactive_server.py]
    args:
      instance:
        regex: ^(my|random)$
        default: random
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  game2stack:
    explain: "Now you have two stack and you can move all pawns you want."
    evaluator: [python, services/game2stack_server.py]
    args:
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
        explain: "Number from 1 to 30, the number of questions posed to the problem solver."
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
        explain: "Any string without space characters but meant to specify one of the services of the problem {problem}"
      lang:
        regex: ^(hardcoded|en|it)$
        default: it

