public_folder: public
services:
    solve:
#        evaluator: [manager/target/release/manager]
        evaluator: [python, manager.py]
        args:
            size:
                regex: ^(tiny|small|medium|big|huge)$
                default: huge
