public_folder: public
services:
  check_one_sol:
    evaluator: [python, services/check_one_sol_server.py]
    args:
      input_treatment:
        regex:  ^((I|H)){0,1000}$
      silent:
        regex: ^(0|1)$
        default: 0
      n:
        regex: ^(free|0|[1-9][0-9]{0,1000})$
        default: free
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_num_sol:
    evaluator: [python, services/check_num_sol_server.py]
    args:
      n_pills:
        regex: ^(0|[1-9][0-9]{0,1}|100)$
      risp:
        regex: ^(0|[1-9][0-9]{0,50})$
        explain: "what you conjecture to be the number of possible treatments given a flask of <n_pills> whole pills"
      ok_if_congruent_modulus:
        regex: ^(0|[1-9][0-9]{0,10})$
#        default: 0
        default: 1000000007
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_num_sol:
    evaluator: [python, services/eval_num_sol_server.py]
    args:
      answ_modulus:
        regex: ^(0|[1-9][0-9]{0,10})$
#        default: 0
        default: 1000000007
      goal:
        regex: ^(correct|efficient)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_sol_set:
    evaluator: [python, services/check_sol_set_server.py]
    args:
      feedback:
        regex: ^(yes_no|tell_a_minimal_missing_prefix|give_one_missing)$
        default: yes_no
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_sol_list:
    evaluator: [python, services/check_sol_list_server.py]
    args:
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesH
      feedback:
        regex: ^(yes_no|spot_first_wrong_consec|tell_first_minimal_missing_prefix|give_first_missing)$
        default: yes_no
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_next_sol:
    evaluator: [python, services/check_next_sol_server.py]
    args:
      current_sol:
        regex:  ^((I|H)){0,1000}$
      next_sol:
        regex:  ^((I|H)){0,1000}$
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      tell_maximal_correct_feedback:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_next:
    evaluator: [python, services/eval_next_server.py]
    args:
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      goal:
        regex: ^(correct|efficient)$
        default: correct
      seed:
        regex: ^([1-9]|[0-9]{2,5})$
        default: 777
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_rank:
    evaluator: [python, services/check_rank_server.py]
    args:
      input_treatment:
        regex:  ^((I|H)){0,1000}$
      rank:
        regex: ^(0|[1-9]|[0-9]{0,300})$
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_unrank:
    evaluator: [python, services/check_unrank_server.py]
    args:
      input_rank:
        regex: ^(0|[1-9]|[0-9]{0,300})$
      treatment:
        regex:  ^((I|H)){0,1000}$
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_rank:
    evaluator: [python, services/eval_rank_server.py]
    args:
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      goal:
        regex: ^(correct|efficient)$
        default: correct
      seed:
        regex: ^([1-9]|[0-9]{2,5})$
        default: 777
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_unrank:
    evaluator: [python, services/eval_unrank_server.py]
    args:
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      goal:
        regex: ^(correct|efficient)$
        default: correct
      seed:
        regex: ^([1-9]|[0-9]{2,5})$
        default: 777
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  gimme_rank:
    evaluator: [python, services/gimme_rank_server.py]
    args:
      treatment:
        regex:  ^((I|H)){0,1000}$
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  gimme_unrank:
    evaluator: [python, services/gimme_unrank_server.py]
    args:
      n_pills:
        regex: ^(0|[1-9][0-9]{0,1}|1000)$
      rank:
        regex: ^(0|[1-9]|[0-9]{0,1000})$
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
  gimme_next_sol:
    evaluator: [python, services/gimme_next_sol_server.py]
    args:
      current_sol:
        regex:  ^((I|H)){0,1000}$
      sorting_criterion:
        regex: ^(lovesI|lovesH)$
        default: lovesI
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
      lang:
        regex: ^(hardcoded|en|it)$
        default: it

