%YAML 1.2
---
public_folder: public
services:
  tell_score:
    explain: "You provide both the secret code and a probing code that will be scored against the secret code according to the rules of the game."
    evaluator: [python, services/tell_score_server.py]
    args:
      secret_code:
        regex: ^((([0-9] *){0,9})|lazy_input)$
        default: lazy_input
      probing_code:
        regex: ^((([0-9] *){0,9})|lazy_input)$
        default: lazy_input
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_scoring_competence:
    explain: "Your scoring competence is assessed. You are given both the secret code and a guessed code that you should score according to the rules."
    evaluator: [python, services/check_scoring_competence_server.py]
    args:
      num_pegs:
        regex: ^([1-9])$
        default: 4
      num_colors:
        regex: ^([2-8])$
        default: 6
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  play:
    evaluator: [python, services/play_server.py]
    args:
      max_num_attempts:
        regex: ^([1-9]|[1-4][0-9]|50)$
        default: 10
        explain: "a number from 1 to 50, the number of questions posed to the problem solver to test the competence"
      num_pegs:
        regex: ^([1-9])$
        default: 4
      num_colors:
        regex: ^([2-8])$
        default: 6
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
      lang:
        regex: ^(hardcoded|en|it)$
        default: it

