public_folder: public
services:
  compact_solution:
    evaluator: [python,services/compact_solution_server.py]
    args:
      m:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 4
      n:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 4
      goal:
        regex: ^(m_plus_n|m_plus_n_half|min)$
        default: m_plus_n
      lang:
        regex: ^(en|it)$
        default: it
  sub_closure:
    evaluator: [python, services/sub_closure_server.py]
    args:
      m:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 3
      n:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 3
      goal:
        regex: ^(any|min)$
        default: min
      lang:
        regex: ^(en|it)$
        default: it
  check_counterexample:
    evaluator: [python, services/check_counterexample_server.py]
    args:
      goal:
        regex: ^(any|minimal)$
        default: any
      lang:
        regex: ^(en|it)$
        default: it
  check_sol:
    evaluator: [python, services/check_sol_server.py]
    args:
      instance:
        regex: ^(my|any)$
        default: any
      coding:
        regex: ^(seq|subset)$
        default: seq
      lang:
        regex: ^(en|it)$
        default: it
  eval_solve:
    evaluator: [python, services/eval_solve_server.py]
    args:
      size:
        regex: ^(small|medium|large)$
        default: medium
      with_NO_cert:
        regex: ^(0|1)$
        default: 1
      lang:
        regex: ^(en|it)$
        default: it
  trilly:
    evaluator: [python, services/eval_solve_server.py]
    args:
      size:
        regex: ^(small|medium|large|huge|unbearable)$
      num_calls:
        regex: ^([1-5]|any)$
        default: 1
      type_calls:
        regex: ^(smaller_m|smaller_n|smaller_m_and_n)$
        default: smaller_m
      lang:
        regex: ^(en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
      lang:
        regex: ^(en|it)$
        default: it
