public_folder: public
services:
    solve:
        evaluator: [python, manager.py]
        args:
            size:
                regex: ^(esempi_testo|smallest|small|medium|big|huge)$
                default: huge
