public_folder: public
services:
  check_one_sol:
    explains: "this service checks whether an input string correctly encodes a tiling of a corridor with '[]' and '[--]' tiles."
    evaluator: [python, services/check_one_sol_server.py]
    args:
      input_formula:
        regex:  ^(\[|\]|-){0,1000}$
        example: "[][][--][]"
      silent:
        explains: "if nothing is wrong with your input string then the service runs silently; otherwise it explains what is the problem in clear."
        regex: ^(0|1)$
        default: 0
      n:
        explains: "set this to require that the corridor length must be a precise value (the tiles '[]' and '[--]' take length 1 and 2, respectively)."
        regex: ^(free|0|[1-9][0-9]{0,1000})$
        default: free
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_num_sol:
    explains: "call this service to check that the number of different tilings with '[]' and '[--]' tiles of a corridor of length <n> is what you think."
    evaluator: [python, services/check_num_sol_server.py]
    args:
      n:
        regex: ^(0|[1-9][0-9]{0,1000})$
        explain: "used to specify the length of the corridor."  
      risp:
        regex: ^(0|[1-9][0-9]{0,100000})$
        explain: "used to specify your conjectured answer for the number of tilings of a corridor of length <n>."  
      ok_if_congruent_modulus:
        explain: "when n grows the number of solutions gets huge. Set this argument to 0 if you are ready to deal with arbitrarily large numbers. Otherwise, computing the number modulo <ok_if_congruent_modulus> will suffice in assessing you got the right ideas."  
        regex: ^(0|[1-9][0-9]{0,10})$
        default: 0
#        default: 1000000007
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      silent:
        explains: "the service runs silently unless your conjectured answer is wrong (or for wrong calls)."
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_num_sol:
    evaluator: [python, services/eval_num_sol_server.py]
    args:
      answ_modulus:
        explain: "when n grows the number of solutions gets huge. Set this argument to 0 if you are ready to deal with arbitrarily large numbers. Otherwise, computing the number modulo <answ_modulus> will suffice in assessing you got the right ideas."  
        regex: ^([1-9][0-9]{0,10}|0)$
#        default: 0
        default: 1000000007
      goal:
        explains: "set your goal (efficient includes also correct)."
        regex: ^(correct|efficient)$
        default: correct
      code_lang: 
        explains: "the more we know about your bot the better we can estimate the efficiency of your algorithm and your approach to provide our best hints."
        regex: ^(python|java|nodejs|compiled)$
        default: python
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_sol_set:
    evaluator: [python, services/check_sol_set_server.py]
    args:
      feedback:
        regex: ^(yes_no|tell_a_minimal_missing_prefix|give_one_missing|tell_prefix_of_missing_len_[1-9][0-9]{0,10})$
        default: yes_no
        explain: the options are as follows
        explain1: -yes_no= just tell me if I am missing one solution.
        explain2: -tell_a_minimal_missing_prefix= please, of one solution I am missing, give me a long enough prefix so that if I complete it to a feasible solution then I get a new one.
        explain3: -give_one_missing= just spoil me out a solution I have missed.
        explain4: -tell_prefix_of_missing_len_?= please, of one solution I am missing, give me the prefix of the specified length.
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_sol_list:
    evaluator: [python, services/check_sol_list_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_short_tiles|loves_long_tiles)$
        default: loves_short_tiles
      feedback:
        regex: ^(yes_no|dispell_first_missing_longest_seen_prefix|spot_first_wrong_consec|tell_first_minimal_missing_prefix|give_first_missing|tell_prefix_of_missing_len_[1-9][0-9]{0,10})$
        default: yes_no
        explain: the options are as follows
        explain1: -yes_no= just tell me if I am missing one solution.
        explain2: -dispell_first_missing_longest_seen_prefix= please, of one solution I am missing, give me the longest prefix it has in common with a solution I have given.
        explain3: -spot_first_wrong_consec= please, point me out two solutions I have placed consecutive whereas at least one missing solutions sits betwen them.
        explain4: -tell_first_minimal_missing_prefix= please, of one solution I am missing, give me a long enough prefix so that if I complete it to a feasible solution I get a new one.
        explain5: -give_first_missing= just spoil me out a solution I have missed.
        explain6: -tell_prefix_of_missing_len_<len>= please, of one solution I am missing, give me the prefix of length <len>.
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_next_sol_gen:
    evaluator: [python, services/check_next_sol_gen_server.py]
    args:
      current_sol:
        regex:  ^(\[|\]|-){0,1000}$
      next_sol:
        regex:  ^(\[|\]|-){0,1000}$
      sorting_criterion:
        regex: ^(loves_short_tiles|loves_long_tiles)$
        default: loves_short_tiles
      tell_maximal_correct_feedback:
        regex: ^(0|1)$
        default: 0
      silent:
        explains: "if nothing is wrong then the service runs silently."
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_next:
    evaluator: [python, services/eval_next_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_short_tiles|loves_long_tiles)$
        default: loves_short_tiles
      goal:
        explains: "set your goal (efficient includes also correct)."
        regex: ^(correct|efficient)$
        default: correct
      seed:
        regex: ^(random_seed|[1-9]|[0-9]{5,5})$
        default: random_seed
        explain: "Called with seed=random_seed, the service chooses its seed at random (and communicates it to the user)"
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
        explains: "the more we know about your bot the better we can estimate the efficiency of your algorithm and your approach to provide our best hints."
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_rank_of_sol:
    evaluator: [python, services/check_rank_of_sol_server.py]
    args:
      n:
        regex: ^(0|[1-9][0-9]{0,50})$
      sorting_criterion:
        regex: ^(loves_short_tiles|loves_long_tiles)$
        default: loves_short_tiles
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_unrank:
    evaluator: [python, services/check_unrank_server.py]
    args:
      n:
        regex: ^(0|[1-9][0-9]{0,50})$
      sorting_criterion:
        regex: ^(loves_short_tiles|loves_long_tiles)$
        default: loves_short_tiles
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_rank:
    evaluator: [python, services/eval_rank_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_short_tiles|loves_long_tiles)$
        default: loves_short_tiles
      goal:
        explains: "set your goal (efficient includes also correct)."
        regex: ^(correct|efficient)$
        default: correct
      seed:
        regex: ^(random_seed|[1-9]|[0-9]{5,5})$
        default: random_seed
        explain: "Called with seed=random_seed, the service chooses its seed at random (and communicates it to the user)"
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
        explains: "the more we know about your bot the better we can estimate the efficiency of your algorithm and your approach to provide our best hints."
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_unrank:
    evaluator: [python, services/eval_unrank_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_short_tiles|loves_long_tiles)$
        default: loves_short_tiles
      goal:
        explains: "set your goal (efficient includes also correct)."
        regex: ^(correct|efficient)$
        default: correct
      seed:
        regex: ^(random_seed|[1-9]|[0-9]{5,5})$
        default: random_seed
        explain: "Called with seed=random_seed, the service chooses its seed at random (and communicates it to the user)"
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
        explains: "the more we know about your bot the better we can estimate the efficiency of your algorithm and your approach to provide our best hints."
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
        

