public_folder: public
services:
    solve:
        evaluator: [python, manager.py]
        args:
            size:
                regex: ^(esempi_testo|array_small|array_medium|mat_small|array_big|mat_medium|mat_big)$
                default: mat_big
