public_folder: public
services:
  is_subseq:
    evaluator: [python, services/is_subseq_server.py]
    args:
      T:
        regex: ^((([1-9][0-9]{0,9} *)*)|lazy_input)$
        default: lazy_input
      S:
        regex: ^((([1-9][0-9]{0,9} *)*)|lazy_input)$
        default: lazy_input
      YES_cert:
        regex: ^(0|1)$
        default: 1      #explain: "underline the subsequence as evidence of positive answers"
      seed:
        regex: ^(S_and_T_proposed_by_problem_solver|random_seed|[1-9][0-9]{5,5})$
        default: S_and_T_proposed_by_problem_solver
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_subseq:
    explain: "Evaluates correctness and efficiency of a program from the problem solver that, given in input two integer sequences T (on a first line) and S (on a second line), decides whether S is a subsequence of T or not (y/n). The evaluation is done on a set of pseudo-random instances (everything is fully reproducible from the seed)."
    evaluator: [python, services/eval_subseq_server.py]
    args:
      seed:
        explain: "specify the numeric code to reproduce the very same set of instances as in a previous run."
        regex: ^(random_seed|[1-9][0-9]{5,5})$
        default: random_seed
      goal:
        regex: ^(correct|efficient)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      cert: 
        explain: if set to 1 the service server program should also return (on a second line, when its first is 'y') a sequence of indexes where S can be read out from T (idexes start from 0).
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_longest_increasing_subseq:
    evaluator: [python, services/check_longest_increasing_subseq_server.py]
    args:
      T:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input)$
        default: lazy_input
      max_len_min_k:
        regex: ^(0|[1-9][0-9]{0,50}|lazy_input)$
        default: lazy_input
      feas_subseq:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input|none)$
        default: lazy_input
      coloring:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input|none)$
        default: none
      feedback_level:
        regex: ^(complete_subseq|subseq_prefix|no_feedback)$
        default: complete_subseq
      more_or_less_hint_if_wrong_max_len_min_k:
        regex: ^(0|1)$
        default: 0
      YES_cert:
        regex: ^(0|1)$
        default: 1
      seed:
        explain: "specify the numeric code to reproduce the very same set of instances as in a previous run."
        regex: ^(random_seed|[1-9][0-9]{5,5})$
        default: random_seed
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_longest_subseq:
    evaluator: [python, services/eval_longest_increasing_subseq_server.py]
    args:
      yield:
        regex: ^(max_len_min_k|a_max_subseq|a_min_col|both)$
        default: max_len_min_k
      feedback_level:
        regex: ^(0|1|2)$
        default: 1
      goal:
        regex: ^(correct|efficient)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      YES_cert:
        regex: ^(0|1)$
        default: 1    #explain: "the evaluated bot is required to also output a certificate on every YES-instance"
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_num_occurrences_of_S_in_T:    #explain: checks the number of different ways S occurs in T
    evaluator: [python, services/check_num_subseq_server.py]
    args:
      T:
        regex: ^((([1-9][0-9]{0,9} *)*)|lazy_input)$
        default: lazy_input
      S:
        regex: ^((([1-9][0-9]{0,9} *)*)|lazy_input)$
        default: lazy_input
      seed:
        explain: "specify the numeric code to reproduce the very same set of instances as in a previous run."
        regex: ^(random_seed|[1-9][0-9]{5,5})$
        default: random_seed
      len_T:
        regex: ^(0|1)$
        default: 0
      risp:
        regex: ^(0|[1-9][0-9]{0,50})$
        default: 0
      ok_if_congruent_modulus:
        regex: ^(0|[1-9][0-9]{0,10})$ 
        default: 1000000007
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_num_occurrences_of_S_in_T:
    evaluator: [python, services/eval_num_subseq_server.py]
    args:
      seed:
        explain: "specify the numeric code to reproduce the very same set of instances as in a previous run."
        regex: ^(random_seed|[1-9][0-9]{5,5})$
        default: random_seed
      answ_modulus:
        regex: ^([1-9][0-9]{0,10})$
#        default: 0
        default: 1000000007
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  
# BEGIN: competenza gestione sottosequenze diverse di una stessa sequenza
#        può avere senso come un esercizio a parte (di programmazione) 
  check_subseq_set:
    evaluator: [python, services/check_subseq_set_server.py]
    args:
      feedback:
        regex: ^(yes_no|tell_a_minimal_missing_prefix|give_one_missing)$
        default: yes_no
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
# può avere senso come esercizio di programmazione, può essere accoppiato al successivo 
  check_subseq_list:
    evaluator: [python, services/check_subseq_list_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      feedback:
        regex: ^(yes_no|spot_first_wrong_consec|tell_first_minimal_missing_prefix|give_first_missing)$
        default: yes_no
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_next_subseq_gen:
    evaluator: [python, services/check_next_subseq_gen_server.py]
    args:
      current_subseq:
        regex:  ^(\(|\)){0,1000}$
      next_subseq:
        regex:  ^(\(|\)){0,1000}$
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      tell_maximal_correct_feedback:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_next_subseq_gen:
    evaluator: [python, services/eval_next_subseq_gen_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_rank_of_seq:
    evaluator: [python, services/check_rank_of_seq_server.py]
    args:
      T:
        regex: ^((([1-9][0-9]{0,9} *)*)|lazy_input)$
        default: lazy_input
      sorting_criterion:
        regex: ^([1-4]|lazy_input)$
        default: lazy_input
      lang:
        regex: ^(hardcoded|en|it)$
        default: it  
  eval_rank_of_seq:
    evaluator: [python, services/eval_rank_of_seq_server.py]
    args:
      goal:
        regex: ^(correct|efficient)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      NO_cert:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
