codename: eggs
public_folder: public
services:
  confirm_min_throws:
    evaluator: services/confirm_min_throws_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      min:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      colored_feedback:
        regex: ^(yes|no)$
        default: no
  opt_move:
    evaluator: services/opt_move_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      colored_feedback:
        regex: ^(yes|no)$
        default: no
  check_table:
    evaluator: services/check_table_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      colored_feedback:
        regex: ^(yes|no)$
        default: no
  play:
    evaluator: services/play_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      colored_feedback:
        regex: ^(yes|no)$
        default: no
  play_murphy:
    evaluator: services/play_murphy_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      colored_feedback:
        regex: ^(yes|no)$
        default: no
