public_folder: public
services:
  confirm_min_throws:
    evaluator: [services/confirm_min_throws_server.py]
    args:
      min:
        regex: ^([1-9][0-9]{0,1}|100)$
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 2
      lang:
        regex: (en|it)
        default: it
  check_table:
    evaluator: [services/check_table_server.py]
    args:
      eggs_from_zero:
        regex: (0|1)
        default: 0
      floors_from_zero:
        regex: (0|1)
        default: 0
      lang:
        regex: (en|it)
        default: it
  gimme_table:
    evaluator: [services/gimme_table_server.py]
    args:
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 10
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 2
      eggs_from_zero:
        regex: (0|1)
        default: 0
      floors_from_zero:
        regex: (0|1)
        default: 0
      lang:
        regex: (en|it)
        default: it
  opt_move:
    evaluator: [services/opt_move_server.py]
    args:
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      tell_min_spoiler:
        regex: (0|1)
        default: 0
      lang:
        regex: (en|it)
        default: it
  play:
    evaluator: [services/play_server.py]
    args:
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      lang:
        regex: (en|it)
        default: it
  play_murphy:
    evaluator: [services/play_murphy_server.py]
    args:
      n_floors:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      n_eggs:
        regex: ^([1-9][0-9]{0,1}|100)$
        default: 100
      lang:
        regex: (en|it)
        default: it
