codename: eggs
attachments_folder: att
services:
  confirm_min_lanci:
    evaluator: confirm_min_throws_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      min:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
      n_floors:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
      n_eggs:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
  opt_move:
    evaluator: opt_move_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
      n_eggs:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
  check_table:
    evaluator: check_table_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
      n_eggs:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
  play:
    evaluator: play_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
      n_eggs:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
  play_murphy:
    evaluator: play_murphy_server.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_floors:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
      n_eggs:
        regex: ([1-9][0-9]{0,1}|100)
        default: 100
