codename: sum
public_folder: public
services:
  sum:
    evaluator: [services/sum/python/advanced/sum_server.py]
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: twodigits
      obj:
        regex: ^(any|max_product)$
        default: any
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
  sum_and_difference:
    evaluator: [services/sum_and_difference/python/advanced/sum_and_difference_server.py]
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
  sum_and_product:
    evaluator: [services/sum_and_product/python/advanced/sum_and_product_server.py]
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
