codename: sum
attachments_folder: public
services:
  sum:
    evaluator: services/python/sum_server.py
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: twodigits
      obj:
        regex: ^(any|max_product)$
        default: any
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      colored_feedback:
        regex: ^(yes|no)$
        default: no
  sum_and_difference:
    evaluator: services/python/sum_and_difference_server.py
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      colored_feedback:
        regex: ^(yes|no)$
        default: no
  sum_and_product:
    evaluator: services/python/sum_and_product_server.py
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      colored_feedback:
        regex: ^(yes|no)$
        default: no
