public_folder: public
services:
  free_sum:
    evaluator: [python, services/free_sum/python/advanced/free_sum_server.py]
    args:
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: twodigits
      obj:
        regex: ^(any|max_product)$
        default: any
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
  sum_and_difference:
    evaluator: [python, services/sum_and_difference/python/advanced/sum_and_difference_server.py]
    args:
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
  sum_and_product:
    evaluator: [python, services/sum_and_product/python/advanced/sum_and_product_server.py]
    args:
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
  help:
    evaluator: [python, services/help/help_server.py]
    args:
      page:
        regex: ^(sum|free_sum|sum_and_difference|sum_and_product)$
        default: sum
      lang:
        regex: ^(en|it)$
        default: it

