codename: sum
attachments_folder: att
services:
  sum:
    evaluator: sum_onserver.py
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(small|big)$
        default: small
      obj:
        regex: ^(any|max_product)$
        default: any
  sum_and_product:
    evaluator: sum_and_product_onserver.py
    args:
      lang:
        regex: ^(en|it)$
        default: it
      numbers:
        regex: ^(small|big)$
        default: small
