codename: sum
attachments_folder: att
services:
  observe:
    evaluator: observe.py
    args:
      lang:
        regex: ^(en|it)$
        default: it
  solve:
    evaluator: solve.py
    args:
      lang:
        regex: ^(en|it)$
        default: it
      subtask:
        regex: ^(small|big)$
        default: small
