%YAML 1.2
---
public_folder: public
services:
  get_my_records:
    evaluator: [python,services/get_my_records_server.py]
    description: To get the records of your rtal sumbissions and know your current scores for a given problem.
    args:
      problem:
        regex: ^(all_problems|lcs|model_lcs)$
        default: all_problems
        explain: 'Select the problem for which to ask a report of your submissions. Use `all_problems` to get a global report of your submissions on all problems.'
      service:
        regex: ^(([a-z]|[A-Z]|_)*)$
        default: all_services
        explain: 'Specify the service the submission to which you want to get a report about. Use `all_services` to get a global report of your submissions on all services of the problem `problem`.'
      download:
        regex: ^(0|1)$
        default: 0
        explain: 'If this flag is set to 1 then a .csv file with the current situation for your sumbissions is downloade in local into the folder whose fullpath is specified by means of the -o flag (if this path is relative it homes from where the service call has been issued).'
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it  
  
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
        explain: any string without space characters but meant to specify one of the services of the problem {problem}
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: en
      metafile:
        regex: ^(main|en|it)$
        default: main
...
