%YAML 1.2
---
public_folder: public
services:
  spot_magic_indexes:
    description: You give us a sorted array of distinct integers and we return you the sorted list of magic indexes.
    evaluator: [python, services/spot_magic_indexes_server.py]
    args:
      input_vector:
        regex:  ^(lazy|(0|-{0,1}[1-9][0-9]{0,3})(,(0|-{0,1}[1-9][0-9]{0,3})){0,1000})$
        default: lazy
        explain: an increasing sequence of integers separated by commas (no spaces).
        example: -12,0,34,56
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  check_magic_indexes:
    description: You give us a sorted vector of distinct integers and the sorted list of its magic indexes. We check it out.
    evaluator: [python, services/check_magic_indexes_server.py]
    args:
      input_vector:
        regex:  ^((0|-{0,1}[1-9][0-9]{0,3})(,(0|-{0,1}[1-9][0-9]{0,3})){0,1000})$
        explain: an increasing sequence of integers separated by commas (no spaces).
        example: -12,0,2,3,34,56
      magic_indexes:
        regex:  ^((0|-{0,1}[1-9][0-9]{0,3})(,(0|-{0,1}[1-9][0-9]{0,3})){0,1000})|$
        explain: the sorted sequence of magic indexes of input_vector (again an increasing sequence of integers separated by commas and no spaces).
        example: 2,3
      feedback:
        regex: ^(silent|yes_no|gimme_one_wrong)$
        default: silent
        explain: "the levels of feedback are as follows:"
        explain1: "[silent]  if magic_indexes is correct then the service runs silently. Otherwise it signals that there is some problem."
        explain2: "[yes_no]  only tells whether magic_indexes is correct or not."
        explain3: "[gimme_one_wrong]  tells whether magic_indexes is correct or not, and in the second case points out precisely one of the errors."
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  gimme_input_vector:
    description: Call this service to ask for an instance, that is, an increasing sequence of integers comprising an input vector.
    evaluator: [python, services/gimme_input_vector_server.py]
    args:
      n:
        regex:  ^([1-9][0-9]{0,1}|1000})$
      seed:
        regex: ^(random_seed|[1-9][0-9]{5,5})$
        default: random_seed
        explain: specify the numeric code to reproduce the very same set of instances as in a previous run. Called with seed=random_seed, the service chooses its seed at random (and communicates it to the user).
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  check_worst_case_num_questions:
    description: You give us a natural n and what you conjecture to be the smallest number r such that there exists a strategy for knowing the truth in at most r queries. We check out your conjecture.
    evaluator: [python, services/check_worst_case_n_questions_server.py]
    args:
      n:
        regex: ^(0|[1-9][0-9]{0,1}|100)$
      risp:
        regex: ^(0|[1-9][0-9]{0,50})$
        explain: the smallest number r such that there exists a strategy for finding out precisely which indexes are magic in at most r queries.
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  gimme_structural_representation:
    description: You provide us a representation of a configuration of a play, and we provide you with a structural representation (simple or reiforced) that you can use in other services.
    evaluator: [python, services/gimme_structural_representation_server.py]
    args:
      r:
        regex: ^([?|,|(-{0,1}[1-9][0-9]{0,3})]*+)$ 
      representation: 
        regex: ^(simple_structural|reinforced_structural|compact_reinforced_structural)$
        default: simple_structural
        explain: "We transform the values you provided into an instance made of <,=,>,?. '<' indicates that the value is smaller than the index, '=' that it is an MI, and '>' that it is greater than the index."
        explain1: "[simple_structural] We just transform the values you provided."
        explain2: "[reinforced_structural] We transform the values you provided and fill in the missing values (where we are able)."
        explain3: "[compact_reinforced_structural] we give you a representation where are indicated in order the numbers of <,=,>,? present in the vector, for example: < < < ? ? ? ? = = = = ? > > > becomes  3< 4? 4= 1? 3>"
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  play1:
    evaluator: [python, services/play1_server.py]
    description: You give us a natural n to start a play, that corresponds to the length of the vector to start a play. The server holds the secret array and you must find out precisely which of its indexes are magic. By spending one dollar, you can ask the server to display the value of an entry of your choice. You have an infinite number of dollars but you want to spend the least possible number of them. If you ask your opponent to play optimally, you can get proven a lower bound on the minimum number of queries in the worst case (which relates to the question with service check_worst_case_num_questions) and the goals above correct make full sense.
    args:
      n:
        regex: ^(0|[1-9][0-9]{0,5}|1000000)$
        explain: "n is the length of the vector that you provide to the server to start a game."
      opponent:
        regex: ^(optimal|random)$
        default: optimal
        explain: "[optimal] you should find out all the magic indexes of a vector, if any, in the minimum number of questions possible. The vector that will be generated by the server will test your strategy in the worst case... "
        explain1: "[random] the vector that will be generated by the server will test your strategy in a random vector configuration." 
      goal:
        regex: ^(correct|at_most_twice_the_opt|opt_plus_one|optimal)$
        default: correct
        explain: "[correct] tells whether your list of magic indexes provided at the end of the game is correct or not."
        explain1: "[at_most_twice_the_opt] you are allowed to ask at most twice as many questions as necessary if you play optimally."
        explain2: "[opt_plus_one] you are allowed to ask at most one additional question as necessary if you play optimally."
        explain3: "[optimal] your goal is to play optimally, i.e., ask as few questions as possible to find all the magic indexes."
      feedback:
        regex: ^(yes_no_goal|how_far|spot_first_gift|spot_every_gift)$
        default: yes_no_goal
        explain: "the levels of feedback are as follows:"
        explain1: "[yes_no_goal]  tells whether your play reaches the goal set when launching the service."
        explain2: "[how_far]  tells how far you are from the goal you have set."
        explain3: "[spot_first_gift]  during the game signals out (in a commented line, not to disturb the bot that could possibly play in your place) your first move where your goal is compromised."
        explain4: "[spot_every_gift]  during the game signals out (in a commented line) every move where you waste one dollar."
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  eval_play1:
  explain: You give us a final configuration of a game you played and a list of positions you asked for during the game, and we evaluate your moves based on the level and feedback chosen. 
    evaluator: [python, services/eval_play1_server.py]
    args:
      config:
        regex: ^([?|,|(-{0,1}[1-9][0-9]{0,3})]*+)$ 
        explain: the final configuration of the game played.
      moves:
        regex:  ^((0|-{0,1}[1-9][0-9]{0,3})(,(0|-{0,1}[1-9][0-9]{0,3})){0,1000})|$
        explain: the sequence of moves performed during the game separated by commas and no spaces).
        example: 4,7,1,5
      goal:
        regex: ^(correct|at_most_twice_the_opt|opt_plus_one|optimal)$
        default: at_most_twice_the_opt
      feedback:
        regex: ^(yes_no_goal|how_far|spot_first_gift|spot_every_gift)$
        default: yes_no_goal
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  play2:
    evaluator: [python, services/play2_server.py]
    description: You give us a natural n to start a play where you hold the secret array and the server must find out precisely which of its indexes are magic. By spending one dollar, the server can ask to you to display the value of an entry of its choice. If you ask your opponent to play optimally, you can get proven a lower bound on the minimum number of queries in the worst case (which relates to the question with service check_worst_case_num_questions).
    args:
      n:
        regex: ^(0|[1-9][0-9]{0,5}|1000000)$
      opponent:
        regex: ^(optimal|random)$
        default: optimal
      feedback:
        regex: ^(only_index|show_me_how)$
        default: only_index
        explain: "the levels of feedback are as follows:"
        explain1: "[only_index]  the server will provide you only the index where it will want to play."
        explain2: "[show_me_how]  the server will explain how has calculated the indexes to play."
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  optimal_move:
    description: You provide us a configuration of a play and we tell you which is/are the optimal move/s.
    evaluator: [python, services/optimal_move_server.py]
    args:
      r:
        regex: ^([?|,|(-{0,1}[1-9][0-9]{0,3})]*+)$
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
        explain: any string without space characters but meant to specify one of the services of the problem {problem}
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
...
