public_folder: public
services:
  check_one_clause_representation:
    evaluator: [python, services/check_one_clause_representation_server.py]
    args:
      clause: 
        regex: ^((\s*!?\s*(x)[1-9])(\s*or\s*!?\s*(x)[1-9])*\s*|lazy_input)$
        default: lazy_input
      representing_formula: 
        regex: ^(\s*\(\s*(\s*!?\s*(x|y)[1-9])(\s*or\s*!?\s*(x|y)[1-9])*\s*\)(\s*and\s*\(\s*(\s*!?\s*(x|y)[1-9])(\s*or\s*!?\s*(x|y)[1-9])*\s*\))*\s*|lazy_input)$
      lang:
        regex: ^(en|it)$
        default: it
  check_f_representation:
    evaluator: [python, services/check_f_representation_server.py]
    args:
      f_k: 
        regex: ^(\s*\(\s*(\s*!?\s*x[1-9])(\s*or\s*!?\s*x[1-9])*\s*\)(\s*and\s*\(\s*(\s*!?\s*x[1-9])(\s*or\s*!?\s*x[1-9])*\s*\))*\s*|lazy_input)$
        default: lazy_input
      f_3: 
        regex: ^(\s*\(\s*(\s*!?\s*(x|y)[1-9])(\s*or\s*!?\s*(x|y)[1-9])*\s*\)(\s*and\s*\(\s*(\s*!?\s*(x|y)[1-9])(\s*or\s*!?\s*(x|y)[1-9])*\s*\))*\s*|lazy_input)$
      lang:
        regex: ^(en|it)$
        default: it
  eval_f_rep:
    evaluator: [python, services/eval_f_rep_server.py]
    args:
      k:
        regex: ^([4-9]|10)$
        default: 4
      size:
        regex: ^(tiny|small|medium|large)$
        default: small
      lang:
        regex: ^(en|it)$
        default: it

