public_folder: public
services:
  check_one_clause_representation:
    evaluator: [python, services/compact_solution_server.py]
    args:
      k: ^([4-9]|10)$
        default: 4
      c: ^()$
      lang:
        regex: ^(en|it)$
        default: it
  check_f_representation:
    evaluator: [python, services/compact_solution_server.py]
    args:
      k: ^([4-9]|10)$
        default: 4
      n: ^([1-9]|[1-2][0-9]|30)$
        default: 4
      f: ^()$
      lang:
        regex: ^(en|it)$
        default: it

