public_folder: public
services:
    solve:
        evaluator: [python, manager.py]
        args:
            size:
                regex: ^(esempi_testo|small|medium|big)$
                default: big
        files:
            - source