%YAML 1.2
---
public_folder: public
services:
	gimme_IP_in_subnet:
		description:"This service takes in a subnet Mask (ex. 255.255.0.0) defining a whole
		define a range of valid IP addresses. The service returns IP address from that range. Use the arguments of the service to specify which
		IP's in the range should be returned."
		evaluator:[gimme_IP_in_subnet.java]
		args:
			subnet_Mask:
				regex: ((\d)+\.)*(\d)*$
				regex-explained: a netmask comprises four field separated by dots. Each field is a number in digital representation.
				example: 255.255.0.0
				explain: a netmask comprises four fields separated by dots. Each field is a number in the closed interval [0-255] in digital representation
			
			output:
				regex: ^(first_IP|last_IP|random_IP|list_all|number)$
				explain: "the options are as follows:"
				explain1: -first_IP= return only the first valid IP of the range
				explain2: -last_IP= return only the last valid IP of the range 
				explain3: -random_IP= return a random_IP in the range (choosen according to the uniform distribution)
				explain4: -list_all: return a list of the IPs in the range in lexicographic order. If random_IP in the range (choos to the uniform distribution)				
				explain4: -number: return only the number of valid IPs in the range
				

			lang:
				regex: ^(hardcoded|hardcoded_ext|en|it)$
				dafault:it
	help:
		evaluator:[]
		args:
			page:
				regex:
				efault:help
			lang:
				regex: ^(en|it)$
        			default: it
	synopsis:
		evaluator:[]
		args:	
			service:
        			regex: ^((\S)+)$
        			default: synopsis
        			explain: 
      			lang:
        			regex: ^(hardcoded|hardcoded_ext|en|it)$
        			default: it
     			metafile:
        			regex: ^(main|en|it)$
       				default: main		
...