%YAML 1.2
---
public_folder: public
services:
  request_new_authorization:
    description: 'Call this service to initiate the process to build a new authorization. .'
    evaluator: [python,services/gimme_instance_server.py]
    args:
      matricola:
        regex: ^(VR......)$
      validity:
        regex: ^(day|week|month)$
        default: day
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  
  check_authorization:
    description: 'Call this service to initiate the process to build a new authorization. .'
    evaluator: [python,services/check_authorization_server.py]
    args:
      matricola:
        regex: ^(VR......)$
      secret:
        regex: ^(day|week|month)$
        default: day
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it

  submit_exam_with_check_authorization:
    args:
      matricola:
        regex: ^(VR......)$
      secret:
        regex: ^(day|week|month)$
        default: day
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it


  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
        explain: any string without space characters but meant to specify one of the services of the problem {problem}
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
      metafile:
        regex: ^(main|en|it)$
        default: main
...

