public_folder: public
services:
  free_sum:
    evaluator: [python, services/free_sum/advanced/free_sum_server.py]
    args:
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: twodigits
      obj:
        regex: ^(any|max_product)$
        default: any
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
  sum_and_difference:
    evaluator: [python, services/sum_and_difference/advanced/sum_and_difference_server.py]
    args:
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
  sum_and_product:
    #evaluator: [python, services/sum_and_product/advanced/sum_and_product_server.py]
    #evaluator: [java, -cp, services/sum_and_product/simple, sum_and_product_server]
    #evaluator: [java, -jar, services/sum_and_product/simple, sum_and_product_server.jar]
    #evaluator: [java, -jar -cp, services/sum_and_product/simple, sum_and_product_server.jar]
    evaluator: [java, -jar, services/sum_and_product/simple/sum_and_product_server.jar]
    args:
      numbers:
        regex: ^(onedigit|twodigits|big)$
        default: onedigit
      num_questions:
        regex: ^([1-9]|[1-2][0-9]|30)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
