codename: number_theory.infinity_of_N
public_folder: public
services:
  bigger_and_bigger:
    evaluator: [services/bigger_and_bigger/python/simple/bigger_and_bigger_server.py]
    args:
      lang:
        regex: ^(en|it)$
        default: it
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 20
  rationals_are_dense_into_reals:
    evaluator: [services/archimede/python/simple/archimede_server.py]
    args:
      lang:
        regex: ^(en|it)$
        default: it
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 10
  archimede:
    evaluator: [services/archimede/python/simple/archimede_server.py]
    args:
      lang:
        regex: ^(en|it)$
        default: it
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 10
