public_folder: public
services:
    solve:
        evaluator: [python, services/manager.py]
        args:
            size:
                regex: ^(esempi_testo|small|medium|big|huge)$
                default: huge
        files:
            - source
