public_folder: public
services:
  common_multiple:
    evaluator: [python, services/common_multiple/python/simple/common_multiple_server.py]
    args:
      num_naturals:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 3
      lang:
        regex: ^(en|it)$
        default: it
  common_non_multiple:
    evaluator: [python, services/common_non_multiple/python/simple/common_non_multiple_server.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 3
      lang:
        regex: ^(en|it)$
        default: it
  extract_prime:
    evaluator: [python, services/extract_prime/python/simple/extract_prime_server.py]
    args:
      n:
        regex: ^(twodigits|fourdigits|big)$
        default: twodigits
      lang:
        regex: ^(en|it)$
        default: it
