codename: morra
public_folder: public
services:
  play:
    evaluator: [services/play/python/advanced/play_server.py]
    args:
      lang:
        regex: (en|it)
        default: it
      num_rounds:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 10
      hash_type:
        regex: ^(rabin_karp|sha1|sha256|sha512)$
        default: rabin_karp
  compute_hash:
    evaluator: [services/compute_hash/python/advanced/compute_hash_server.py]
    args:
      lang:
        regex: (en|it)
        default: it
      white_string:
        regex: ^([[:alnum:]]|_){4,100}$
        default: None
      hash_type:
        regex: ^(rabin_karp|sha1|sha256|sha512)$
        default: rabin_karp
  verify_hash:
    evaluator: [services/verify_hash/python/advanced/verify_hash_server.py]
    args:
      lang:
        regex: (en|it)
        default: it
      num_checks:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 100
      hash_type:
        regex: ^(rabin_karp|sha1|sha256|sha512)$
        default: rabin_karp
      alphabet_white_string:
        regex: ^(safely_printable|ascii_letters|digits|punctuation|ascii_uppercase|ascii_lowercase)$
        default: safely_printable
      length_white_string:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 64  
