codename: morra
public_folder: att
services:
  play:
    evaluator: player.py
    args:
      lang:
        regex: (en|it)
        default: it
      num_rounds:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 10
      hash:
        regex: ^(rabin_karp|SHA-1)$
        default: rabin_karp
  compute_hash:
    args:
      lang:
        regex: (en|it)
        default: it
      clean_string: ^[[:alnum:]]{4,70}$
      hash:
        regex: ^(rabin_karp|SHA-1)$
        default: rabin_karp
  verify_hash:
    args:
      lang:
        regex: (en|it)
        default: it
      num_checks:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 100
      hash:
        regex: ^(rabin_karp|SHA-1)$
        default: rabin_karp
  
