codename: morra
public_folder: att
services:
  play:
    evaluator: services/python/player.py
    args:
      lang:
        regex: (en|it)
        default: it
      num_rounds:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 10
      hash:
        regex: ^(rabin_karp|SHA-1)$
        default: rabin_karp
  compute_hash: services/python/compute_hash.py
    args:
      lang:
        regex: (en|it)
        default: it
      white_string:
        regex: ^([[:alnum:]]|_){4,100}$
        default: 0000
      hash:
        regex: ^(rabin_karp|SHA-1)$
        default: rabin_karp
  verify_hash: services/python/verify_hash.py
    args:
      lang:
        regex: (en|it)
        default: it
      num_checks:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 100
      hash:
        regex: ^(rabin_karp|SHA-1)$
        default: rabin_karp
      length:
        regex: ^(rabin_karp|SHA-1)$
        default: 64
  
