codename: morra
public_folder: att
services:
  play:
    evaluator: player.py
    args:
      lang:
        regex: (en|it)
        default: it
      n_rounds:
        regex: [1-9][0-9]{0,2}
        default: 10
