public_folder: public
services:
  is_subseq:
    evaluator: [python, services/is_subseq_server.py]
    args:
      T:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input)$
        default: lazy_input
      s:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input)$
        default: lazy_input
      YES_cert:
        regex: ^(0|1)$
        default: 1
      lang:
        regex: ^(en|it)$
        default: it
  eval_subseq:
    evaluator: [python, services/eval_subseq_server.py]
    args:
      YES_cert:
        regex: ^(0|1)$
        default: 1
      lang:
        regex: ^(en|it)$
        default: it
  check_num_s_in_all_different_T:
    evaluator: [python, services/eval_subseq_server.py]
    args:
      len_T:
        regex: ^(0|1)$
      risp:
        regex: ^(0|[1-9][0-9]{0,50})$
      ok_if_congruent_modulus:
        regex: ^(0|[1-9][0-9]{0,10})$
#        default: 0
        default: 1000000007
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(en|it)$
        default: it

# BEGIN: competenza gestione sottosequenze diverse di una stessa sequenza
  check_num_subseq:
    evaluator: [python, services/check_num_subseq_server.py]
    args:
      num_pairs:
        regex: ^(0|[1-9][0-9]{0,1}|100)$
      risp:
        regex: ^(0|[1-9][0-9]{0,50})$
      ok_if_congruent_modulus:
        regex: ^(0|[1-9][0-9]{0,10})$
#        default: 0
        default: 1000000007
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(en|it)$
        default: it
  eval_num_subseq:
    evaluator: [python, services/eval_num_subseq_server.py]
    args:
      answ_modulus:
        regex: ^([1-9][0-9]{0,10})$
#        default: 0
        default: 1000000007
      lang:
        regex: ^(en|it)$
        default: it
  check_subseq_set:
    evaluator: [python, services/check_subseq_set_server.py]
    args:
      feedback:
        regex: ^(yes_no|tell_a_minimal_missing_prefix|give_one_missing)$
        default: yes_no
      lang:
        regex: ^(en|it)$
        default: it
  check_subseq_list:
    evaluator: [python, services/check_subseq_list_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      feedback:
        regex: ^(yes_no|spot_first_wrong_consec|tell_first_minimal_missing_prefix|give_first_missing)$
        default: yes_no
      lang:
        regex: ^(en|it)$
        default: it
  check_next_subseq_gen:
    evaluator: [python, services/check_next_subseq_gen_server.py]
    args:
      current_subseq:
        regex:  ^(\(|\)){0,1000}$
      next_subseq:
        regex:  ^(\(|\)){0,1000}$
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      tell_maximal_correct_feedback:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(en|it)$
        default: it
  eval_next_subseq_gen:
    evaluator: [python, services/eval_next_subseq_gen_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(en|it)$
        default: it
  check_rank_of_subseq:
    evaluator: [python, services/check_rank_of_subseq.py]
    args:
      one_formula:
        regex:  ^(\(|\)){0,1000}$
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(en|it)$
        default: it
  check_subseq_of_rank:
    evaluator: [python, services/check_subseq_of_rank.py]
    args:
      num_pairs:
        regex: ^([1-9][0-9]{0,1}|100)$
      rank:
        regex: ^([1-9]|1[0-9]{0,1}|20)$
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(en|it)$
        default: it
  eval_rank_of_subseq:
    evaluator: [python, services/eval_rank_of_subseq.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(en|it)$
        default: it
  eval_subseq_of_rank:
    evaluator: [python, services/eval_subseq_of_rank.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(en|it)$
        default: it

# END: competenza gestione sottosequenze diverse di una stessa sequenza

  check_longest_subseq:
    evaluator: [python, services/check_longest_subseq_server.py]
    args:
      T:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input)$
        default: lazy_input
      max_len_min_k:
        regex: ^(0|[1-9][0-9]{0,50}|lazy_input)$
        default: lazy_input
      feas_subseq:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input|none)$
        default: lazy_input
      coloring:
        regex: ^((([1-9][0-9]{0,9} )*[1-9][0-9]{0,9})|lazy_input|none)$
        default: none
      more_or_less_hint_if_wrong_max_len_min_k:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(en|it)$
        default: it
  eval_longest_subseq:
    evaluator: [python, services/eval_longest_subseq_server.py]
    args:
      yield:
        regex: ^(max_len_min_k|a_max_subseq|a_min_col|both)$
        default: max_len_min_k
      feedback_level:
        regex: ^(0|1|2)$
        default: 1
      lang:
        regex: ^(en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
      lang:
        regex: ^(en|it)$
        default: it

