public_folder: public
services:
  bigger_and_bigger:
    evaluator: [python, services/bigger_and_bigger/simple/bigger_and_bigger_server.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 20
      lang:
        regex: ^(en|it)$
        default: it
  rationals_are_dense_into_reals:
    evaluator: [python, services/archimede/simple/archimede_server.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
  archimede:
    evaluator: [python, services/archimede/simple/archimede_server.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,3}|1000)$
        default: 10
      lang:
        regex: ^(en|it)$
        default: it
