public_folder: public
services:
  check_one_sol:
    evaluator: [python, services/check_one_sol_server.py]
    args:
      input_formula:
        regex:  ^(\(|\)){0,1000}$
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_num_sol:
    evaluator: [python, services/check_num_sol_server.py]
    args:
      num_pairs:
        regex: ^(0|[1-9][0-9]{0,1}|100)$
      risp:
        regex: ^(0|[1-9][0-9]{0,50})$
        explain: "what you conjecture to be the number of well-formed formulas on <num_pairs> parentheses"
      ok_if_congruent_modulus:
        regex: ^(0|[1-9][0-9]{0,10})$
#        default: 0
        default: 1000000007
      more_or_less_hint_if_wrong:
        regex: ^(0|1)$
        default: 0
      silent:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_num_sol:
    evaluator: [python, services/eval_num_sol_server.py]
    args:
      answ_modulus:
        regex: ^([1-9][0-9]{0,10}|0)$
#        default: 0
        default: 1000000007
      goal:
        regex: ^(correct|efficient)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: python
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_sol_set:
    evaluator: [python, services/check_sol_set_server.py]
    args:
      feedback:
        regex: ^(yes_no|tell_a_minimal_missing_prefix|give_one_missing)$
        default: yes_no
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_sol_list:
    evaluator: [python, services/check_sol_list_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_closing_par
      feedback:
        regex: ^(yes_no|spot_first_wrong_consec|tell_first_minimal_missing_prefix|give_first_missing)$
        default: yes_no
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_next_sol_gen:
    evaluator: [python, services/check_next_sol_gen_server.py]
    args:
      current_sol:
        regex:  ^(\(|\)){0,1000}$
      next_sol:
        regex:  ^(\(|\)){0,1000}$
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      tell_maximal_correct_feedback:
        regex: ^(0|1)$
        default: 0
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_next_sol_gen:
    evaluator: [python, services/eval_next_sol_gen_server.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      goal:
        regex: ^(correct|fast)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: correct
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_rank_of_sol:
    evaluator: [python, services/check_rank_of_sol.py]
    args:
      one_formula:
        regex:  ^(\(|\)){0,1000}$
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  check_unrank:
    evaluator: [python, services/check_unrank.py]
    args:
      num_pairs:
        regex: ^([1-9][0-9]{0,1}|100)$
      rank:
        regex: ^([1-9]|1[0-9]{0,1}|20)$
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_rank_of_sol:
    evaluator: [python, services/eval_rank_of_sol.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      goal:
        regex: ^(correct|fast)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: correct
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  eval_unrank:
    evaluator: [python, services/eval_unrank.py]
    args:
      sorting_criterion:
        regex: ^(loves_opening_par|loves_closing_par)$
        default: loves_opening_par
      goal:
        regex: ^(correct|fast)$
        default: correct
      code_lang: 
        regex: ^(python|java|nodejs|compiled)$
        default: correct
      lang:
        regex: ^(hardcoded|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_server.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
      lang:
        regex: ^(hardcoded|en|it)$
        default: it

