%YAML 1.2
---
public_folder: public
services:
  common_multiple:
    evaluator: [python, services/common_multiple/simple/common_multiple_driver.py]
    args:
      num_naturals:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 3
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  common_non_multiple:
    evaluator: [python, services/common_non_multiple/simple/common_non_multiple_driver.py]
    args:
      num_rounds:
        regex: ^([1-9][0-9]{0,2}|100)$
        default: 3
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  extract_prime:
    evaluator: [python, services/extract_prime/simple/extract_prime_driver.py]
    args:
      n:
        regex: ^(twodigits|fourdigits|big)$
        default: twodigits
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
  synopsis:
    evaluator: [python, services/synopsis/synopsis_driver.py]
    args:
      service:
        regex: ^((\S)+)$
        default: synopsis
        explain: any string without space characters but meant to specify one of the services of the problem %(problem)s
      lang:
        regex: ^(hardcoded|hardcoded_ext|en|it)$
        default: it
      metafile:
        regex: ^(main|en|it)$
        default: main
...
